services:
  - type: web
    name: lab-reservas
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: SENDGRID_API_KEY
        sync: false  # Lo defines manualmente en el dashboard de Render
